config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"
  devise_for :users

  resources :users, only: [ :show ]
  resources :events
  resources :guests, only: [ :create, :destroy, :new ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :location, presence: true
  validates :date, presence: true

  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :guests, dependent: :destroy
  has_many :attendees, -> { where("guests.access = ?", 0) },
            through: :guests, source: :user
  has_many :invited_attendees, -> { where("guests.access = ?", 1) },
            through: :guests, source: :user


  scope :upcoming, -> { where("date >= ?", Date.current) }

  scope :past, -> { where("date < ?", Date.current) }

  def own_event(current_user_ID)
    self.user_id == current_user_ID
  end

  def not_attended?(current_user_ID)
    Guest.find_by(user_id: current_user_ID, event_id: self.id, access: :attending).nil?
  end

  def upcoming_event?
    self.date >= Date.current
  end
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :user
  belongs_to :event

  enum :access, { attending: 0, invited: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :events, dependent: :destroy
  has_many :guests, dependent: :destroy
  has_many :attended_events, -> { where("guests.access = ?", 0) },
             through: :guests, source: :event

  has_many :invited_events, -> { where("guests.access = ?", 1) },
              through: :guests, source: :event

  def invited_events_not_attended
    @events_invited = self.invited_events.upcoming
    @events_attending = self.attended_events.upcoming

    @invited_events_not_attended = @events_invited - @events_attending

    Event.where(id: @invited_events_not_attended.map(&:id))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :first_name, :last_name, :email, :password ])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :private_event, only: [ :show ]
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path, status: :see_other
  end


  private
  def event_params
    params.require(:event).permit(:location, :date, :private)
  end

  def private_event
    @event = Event.find(params[:id])
    unless @event.invited_attendees.include?(current_user) ||
          @event.private == false ||
          @event.creator == current_user
      flash[:notice] = "Only invited guests may view this event"
      redirect_to root_path
    end
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def new
    @event = Event.find(guest_params["event_id"])
    @users = User.all
  end
  def create
    if guest_params["access"] == "attending"
      @guest = current_user.guests.build(guest_params)

      @guest.save

      flash[:notice] = "You have successfully signed up for the event"
      redirect_to event_path(guest_params["event_id"])
    else
      @user = User.find(guest_params["user_id"])
      @guest = @user.guests.build(guest_params)

      @guest.save

      redirect_to new_guest_path
    end
  end

  def destroy
    if guest_params["access"] == "attending"
      @guest = current_user.guests.find_by(guest_params)
      @guest.destroy

      flash[:notice] = "Successfully unattended event"
      redirect_to event_path(guest_params["event_id"])
    else
      @guests = Guest.where(event_id: guest_params["event_id"],
                          user_id: guest_params["user_id"])

      @guests.each do |guest|
        guest.destroy
      end

      redirect_to new_guest_path
    end
  end

  private

  def guest_params
    params.permit(:event_id, :access, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :view_own_page_only, only: [ :show ]
  def show
    @events = User.find(params[:id]).events
  end

  private

  def view_own_page_only
    @user = User.find(params[:id])

    if current_user != @user
      flash[:notice] = "You can only view your own user page"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event-list.html.erb
<div class="events">
    <% events.order(:date).each do |event| %>
        <% if event.private == false || event.invited_attendees.include?(current_user) || event.creator == current_user %>
            <div class="event-card">
                <div class="event-location">
                    <span><%= event.location %> </span>
                    <% if event.private == true %>
                        (Private Event)
                    <% end %>
                </div>
                <div class="event-date"><%= event.date %></div>
                <%= link_to event_path(event) do %>
                    See Details
                <% end %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/events/_form.html.erb
<%= form_with model: event do |form|%>
    <div class="field">
        <%= form.label :location %>
        <%= form.text_field :location %>
    </div>
    <% event.errors.full_messages_for(:location).each do |message |%>
        <div class="message">
            <%= message %>
        </div>
    <% end %>
    <div class="field">
        <%= form.label :date %>
        <%= form.date_field :date %>

    </div>
    <% event.errors.full_messages_for(:date).each do |message| %>
        <div class="message">
            <%= message%>
        </div>
    <% end %>
    <div class="field private">
        <%= form.label :private, "Private" %>
        <%= form.checkbox :private %>
    </div>
    <div class="form-create-button">
        <%= form.submit button%>
    </div>
<% end %>

app/views/events/edit.html.erb
<div class="event-form">
    <h2>Edit Event</h2>
    
    <%= render "form", event: @event, button: "Update" %>
</div>

app/views/events/index.html.erb
<div class="container">
    <div class="events-container">
        <h2>Upcoming Events</h2>

        <%= render "event-list", events: @events.upcoming %>
    </div>
    <div class="events-container">
        <h2>Past Events </h2>

        <%= render "event-list", events: @events.past %>
    </div>
</div>

app/views/events/new.html.erb
<div class="event-form">
    <h2>Create Event</h2>
    
    <%= render "form", event: @event, button: "Create" %>
</div>

app/views/events/show.html.erb
<div class="show-event-container">
    <div class="event-details">
        <h2>Event Details</h2>
        
        <div class="event-detail-value">
            <div class="detail">Hosted by: </div>
            <div class="value"><%= @event.creator.first_name %></div>
        </div>
        <div class="event-detail-value">
            <div class="detail">Location: </div>
            <div class="value"><%= @event.location %></div>
        </div>
        <div class="event-detail-value">
            <div class="detail">Date: </div>
            <div class="value"><%= @event.date %></div>
        </div>
        <% if user_signed_in? %>
            <% if @event.own_event(current_user.id) %>
                <div class="event-attend-edit-buttons">
                    <div class="event-button">
                        <%= link_to edit_event_path(@event) do %>
                            <div>Edit</div>
                        <% end %>
                    </div>
                    <% if @event.private == true && @event.upcoming_event? %>
                        <div class="event-button">
                            <%= link_to new_guest_path(event_id: @event.id) do %>
                                <div>Edit Invites</div>
                            <% end %>
                        </div>
                    <% end %>
                    <div class="event-button">
                        <%= link_to event_path(@event),
                        data: { turbo_method: :delete,
                                turbo_confirm: "Are you sure?"} do %>
                            <div>Delete</div>
                        <% end %>
                    </div>
                </div>
            <% else %>
                <% if @event.upcoming_event? %>
                    <div class="event-attend-edit-buttons">
                        <% if @event.not_attended?(current_user.id) %>
                            <div class="event-button attend">
                                <%= link_to  guests_path(event_id: @event.id, access: :attending),
                                    data: { turbo_method: :post } do %>
                                    Attend
                                <% end %>
                            </div>
                        <% else %>
                            <div class="event-button attend">
                                <%= link_to  guest_path(event_id: @event.id, access: :attending),
                                    data: { turbo_method: :delete,
                                            turbo_confirm: "Are you sure?" } do %>
                                    <div>Unattend</div>
                                <% end %>
                            </div>
                        <% end %>
                    </div>
                <% end %>
            <% end %>
        <% end %>
    </div>
    
    <div class="event-users">
        <div class="event-attendees">
            <h2>Attendees</h2>
        
            <div class="attendees-container">
                <ul>
                    <% @event.attendees.each do |user| %>
                        <li>
                            <%= user.first_name %> <%= user.last_name%>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
        
        <% if @event.private %>
            <div class="event-invited-guests">
                <h2>Invited Guests</h2>
                <div class="invite-list">
                    <ul>
                        <% @event.invited_attendees.each do |guest| %>
                            <li>
                                <%= guest.first_name %> <%= guest.last_name %>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        <% end %>
    </div>

</div>

app/views/guests/new.html.erb
<div class="invites-page">
  
    <div class="heading">
        <h2>Invite Guests to
        <%= link_to event_path(@event) do %>
            <%= @event.location %>
        <% end %>
        </h2>
    </div>
    
    <div class="users-container">
        <ul>
            <% @users.each do |user| %>
                <% unless user.id == current_user.id %>
                    <li>
                        <div class="name">
                            <%= user.first_name %>
                            <%= user.last_name %>
                        </div>
                        <div class="invite">
                            <% if @event.invited_attendees.include?(user)%>
                                <%= link_to  guest_path(id: 0, event_id: @event.id, access: :invited, user_id: user.id),
                                    data: { turbo_method: :delete } do %>
                                        Uninvite
                                <% end %>
                            <% else %>
                                <%= link_to guests_path(event_id: @event.id, access: :invited, user_id: user.id),
                                                    data: {turbo_method: :post} do %>
                                        Invite
                                <% end %>
                            <% end %>
                        </div>
                    </li>
                <% end %>
            <% end %>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navigation">

      <% if user_signed_in? %>
        <div class="username">
          welcome, <%= current_user.first_name%>
        </div>
        <div class="nav-links">
          <%= link_to root_path, class: "home" do %>
            <div>
              Events
            </div>
          <% end %>
          <%= link_to user_path(current_user) do %>
            <div>
              My Events
            </div>
          <% end %>
          <%= link_to new_event_path do %>
            <div>
              Create Event
            </div>
          <% end %>
        </div>
        <%= link_to destroy_user_session_path, data: {
          turbo_method: :delete } do %>
          <div class="logout">
            Logout
          </div>
        <% end %>
      <% else %>
        <%= link_to root_path do %>
          <div>
            Events
          </div>
        <% end %>
        <%= link_to new_user_session_path do %>
          <div>
            Login
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="alerts">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/_events.html.erb
<div class="events">
    <% events.each do |event| %>
        <div class="event-card">
            <div class="event-location"><%= event.location %></div>
            <div class="event-date"><%= event.date %></div>
            <%= link_to event_path(event) do %>
                <div class="event-link">See Details</div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="events-container">
        <h2>Own Events</h2>
    
        <%= render "events/event-list", events: @events.upcoming %>
    </div>
    
    <div class="events-container">
        <h2>Event Invitations</h2>
    
        <%= render "events/event-list", events: current_user.invited_events_not_attended %>
    </div>
    
    <div class="events-container">
        <h2>Events Attending</h2>
    
        <%= render "events/event-list",
        events: current_user.attended_events.where("date >= ?", Date.current ) %>
    </div>
    
    <div class="events-container">
        <h2>Past Own Events</h2>
    
        <%= render "events/event-list", events: @events.past%>
    </div>
    
    <div class="events-container">
        <h2>Past Events Attended</h2>
    
        <%= render "events/event-list",
        events: current_user.attended_events.where("date < ?", Date.current ) %>
    </div>
</div>